import {
  Landmark,
  Wallet,
  CircleUserRound,
  Plus,
  CreditCard,
  CirclePlus,
  ShieldPlus,
  ImagePlus,
  LineChart,
  LayoutGrid,
  ArrowLeft,
  ChevronDown,
  ArrowRight,
  ArrowUp,
  ClipboardList,
  BookOpen,
  BarChart3,
  Droplet,
  Book,
  Building2,
  Calendar,
  CalendarDays,
  Megaphone,
  XCircle,
  Tag,
  MessageSquare,
  Check,
  CheckCircle2,
  ListChecks,
  ChevronLeft,
  ChevronRight,
  GraduationCap,
  X,
  CloudUpload,
  Database,
  CalendarRange,
  Trash2,
  FileText,
  LayoutDashboard,
  CheckCheck,
  Download,
  GripVertical,
  Pencil,
  FileEdit,
  SquarePen,
  CircleAlert,
  CalendarCheck,
  CalendarX,
  Armchair,
  CalendarClock,
  Smile,
  ClipboardCheck,
  Users,
  ListFilter,
  PlaneTakeoff,
  Bold,
  Italic,
  List,
  ListOrdered,
  Underline,
  MessagesSquare,
  Award,
  CircleHelp,
  UserCheck,
  Image,
  Info,
  Globe,
  Link2,
  Library,
  MapPin,
  LogOut,
  Mail,
  DoorOpen,
  Menu,
  CircleSlash,
  MoreHorizontal,
  MoreVertical,
  BellRing,
  Bell,
  BadgeCheck,
  Clock,
  User,
  UserPlus,
  UserX,
  Phone,
  PieChart,
  Printer,
  Brain,
  Send,
  FileQuestion,
  Receipt,
  Save,
  FlaskConical,
  Search,
  Settings,
  FileBarChart,
  Table,
  Table2,
  CircleCheckBig,
  TrendingDown,
  TrendingUp,
  Upload,
  Eye,
  EyeOff,
  TriangleAlert,
  History,
  Minus,
  type LucideIcon,
} from "lucide-react";

/**
 * Maps the Material Symbols icon names used throughout the Stitch export
 * onto Lucide equivalents (per the required tech stack). Layout, color and
 * spacing around each icon are unchanged — only the glyph family differs.
 */
export const iconMap: Record<string, LucideIcon> = {
  account_balance: Landmark,
  account_balance_wallet: Wallet,
  account_circle: CircleUserRound,
  add: Plus,
  add_card: CreditCard,
  add_circle: CirclePlus,
  add_moderator: ShieldPlus,
  add_photo_alternate: ImagePlus,
  analytics: LineChart,
  apps: LayoutGrid,
  arrow_back: ArrowLeft,
  arrow_drop_down: ChevronDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  assignment: ClipboardList,
  auto_stories: BookOpen,
  bar_chart: BarChart3,
  bloodtype: Droplet,
  book: Book,
  business: Building2,
  calendar_month: Calendar,
  calendar_today: CalendarDays,
  campaign: Megaphone,
  cancel: XCircle,
  category: Tag,
  chat: MessageSquare,
  check: Check,
  check_circle: CheckCircle2,
  checklist: ListChecks,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  class: GraduationCap,
  close: X,
  cloud_upload: CloudUpload,
  corporate_fare: Building2,
  credit_card: CreditCard,
  dashboard: LayoutDashboard,
  database: Database,
  date_range: CalendarRange,
  delete: Trash2,
  description: FileText,
  domain: Building2,
  done: Check,
  done_all: CheckCheck,
  download: Download,
  drag_indicator: GripVertical,
  edit: Pencil,
  edit_document: FileEdit,
  edit_note: SquarePen,
  error: CircleAlert,
  event: CalendarDays,
  event_available: CalendarCheck,
  event_busy: CalendarX,
  event_seat: Armchair,
  event_upcoming: CalendarClock,
  expand_more: ChevronDown,
  face: Smile,
  fact_check: ClipboardCheck,
  family_restroom: Users,
  filter_list: ListFilter,
  flight_takeoff: PlaneTakeoff,
  format_bold: Bold,
  format_italic: Italic,
  format_list_bulleted: List,
  format_list_numbered: ListOrdered,
  format_underlined: Underline,
  forum: MessagesSquare,
  grade: Award,
  group: Users,
  groups: Users,
  help: CircleHelp,
  how_to_reg: UserCheck,
  image: Image,
  info: Info,
  insights: LineChart,
  language: Globe,
  link: Link2,
  list_alt: ListChecks,
  local_library: Library,
  location_on: MapPin,
  logout: LogOut,
  mail: Mail,
  meeting_room: DoorOpen,
  menu: Menu,
  menu_book: BookOpen,
  military_tech: Award,
  money_off: CircleSlash,
  more_horiz: MoreHorizontal,
  more_vert: MoreVertical,
  notification_important: BellRing,
  notifications: Bell,
  paid: BadgeCheck,
  payments: Wallet,
  pending: Clock,
  pending_actions: Clock,
  person: User,
  person_add: UserPlus,
  person_off: UserX,
  phone: Phone,
  picture_as_pdf: FileText,
  pie_chart: PieChart,
  point_of_sale: CreditCard,
  print: Printer,
  psychology: Brain,
  publish: Send,
  quiz: FileQuestion,
  remove: Minus,
  receipt_long: Receipt,
  save: Save,
  schedule: Clock,
  school: GraduationCap,
  science: FlaskConical,
  search: Search,
  send: Send,
  settings: Settings,
  summarize: FileBarChart,
  table_chart: Table,
  table_view: Table2,
  task_alt: CircleCheckBig,
  today: CalendarDays,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  upload: Upload,
  view_module: LayoutGrid,
  visibility: Eye,
  visibility_off: EyeOff,
  warning: TriangleAlert,
  work_history: History,
  workspace_premium: Award,
};

export type IconName = keyof typeof iconMap;
